#!/usr/bin/env bash
: ${TI89_PORT:=8080}

if [[ -f .cid ]]; then
  docker stop `cat .cid`
  docker rm   `cat .cid`
  rm .cid
fi

docker run \
  -p ${TI89_PORT}:80 \
  --restart=unless-stopped \
  --cidfile .cid \
  --name ti89-simulator \
  -v $(pwd):/usr/share/nginx/html:ro \
  -d nginx:alpine
